# .github/workflows/daily_run.yml

name: Scrybe AI - Daily Market Analysis

on:
  # Schedule to run at 2:00 AM IST from Tuesday to Saturday.
  # CRON timing is in UTC. 2:00 AM IST is 8:30 PM UTC on the PREVIOUS day.
  # So, '30 20 * * 1-5' means:
  # - Mon 20:30 UTC -> Tue 02:00 IST (Analyzes Monday's data)
  # - Tue 20:30 UTC -> Wed 02:00 IST (Analyzes Tuesday's data)
  # - ...and so on, until...
  # - Fri 20:30 UTC -> Sat 02:00 IST (Analyzes Friday's data)
  schedule:
    - cron: '30 20 * * 1-5'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-daily-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check if the last market day was open
        # This script correctly checks the PREVIOUS day (or Friday if it's Monday UTC).
        # This prevents the job from running on Tuesday morning if Monday was a holiday.
        run: python check_market_open.py

      - name: Run Daily Analysis Script
        # This is the critical step: we run the CORRECT script now.
        env:
          # Pass ALL required secrets from GitHub to the script
          ANALYSIS_DB_URI: ${{ secrets.ANALYSIS_DB_URI }}
          SCHEDULER_DB_URI: ${{ secrets.SCHEDULER_DB_URI }}
          NEWSAPI_API_KEY: ${{ secrets.NEWSAPI_API_KEY }}
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
          
          # Pass the entire pool of Gemini API keys
          GOOGLE_API_KEY_1: ${{ secrets.GOOGLE_API_KEY_1 }}
          GOOGLE_API_KEY_2: ${{ secrets.GOOGLE_API_KEY_2 }}
          GOOGLE_API_KEY_3: ${{ secrets.GOOGLE_API_KEY_3 }}
          GOOGLE_API_KEY_4: ${{ secrets.GOOGLE_API_KEY_4 }}
          GOOGLE_API_KEY_5: ${{ secrets.GOOGLE_API_KEY_5 }}
          GOOGLE_API_KEY_6: ${{ secrets.GOOGLE_API_KEY_6 }}
          GOOGLE_API_KEY_7: ${{ secrets.GOOGLE_API_KEY_7 }}
          GOOGLE_API_KEY_8: ${{ secrets.GOOGLE_API_KEY_8 }}
          GOOGLE_API_KEY_9: ${{ secrets.GOOGLE_API_KEY_9 }}
          GOOGLE_API_KEY_10: ${{ secrets.GOOGLE_API_KEY_10 }}
        run: python run_daily_jobs.py

      - name: Send Daily Report
        # This step only runs if the analysis script above completes successfully
        if: success()
        env:
          ANALYSIS_DB_URI: ${{ secrets.ANALYSIS_DB_URI }}
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
        run: python send_daily_report.py