name: Scrybe AI - Daily Analysis and Report

on:
  # Your regular schedule remains active
  schedule:
    - cron: '30 14 * * 1-5'

  # This section enables manual runs with a special option
  workflow_dispatch:
    inputs:
      force_run:
        description: 'Force run even if market was closed'
        required: true
        type: boolean
        default: false

jobs:
  run_daily_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --index-url https://pypi.org/simple/ pandas-ta==0.3.14b
          pip install -r requirements.txt

      # This step will be SKIPPED if you force the run
      - name: Check Market Status
        id: market_status
        if: github.event.inputs.force_run == false
        run: python check_market_open.py

      # This step runs if the market check passes OR if you force the run
      - name: Run Main Orchestrator
        if: success() || github.event.inputs.force_run == true
        env:
          ANALYSIS_DB_URI: ${{ secrets.ANALYSIS_DB_URI }}
          SCHEDULER_DB_URI: ${{ secrets.SCHEDULER_DB_URI }}
          GOOGLE_API_KEY_1: ${{ secrets.GOOGLE_API_KEY_1 }}
          GOOGLE_API_KEY_2: ${{ secrets.GOOGLE_API_KEY_2 }}
          # Add all other required secrets
          NEWSAPI_API_KEY: ${{ secrets.NEWSAPI_API_KEY }}
        run: python main_orchestrator.py --mode live

      # This step runs if the orchestrator passes OR if you force the run
      - name: Send Daily Report
        if: success() || github.event.inputs.force_run == true
        env:
          ANALYSIS_DB_URI: ${{ secrets.ANALYSIS_DB_URI }}
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          NEWSAPI_API_KEY: ${{ secrets.NEWSAPI_API_KEY }}
        run: python send_daily_report.py