name: Scrybe AI - Daily Market Analysis

on:
  schedule:
    # Runs at 17:00 UTC Monday-Friday (which is 10:30 PM IST)
    - cron: '00 17 * * 1-5'
  workflow_dispatch:

jobs:
  run-daily-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Check if yesterday was a trading day
        id: market_check
        run: python check_market_open.py
        continue-on-error: true

      - name: Run Daily Analysis Script
        if: steps.market_check.outcome == 'success'
        env:
          # Angel One Credentials
          ANGELONE_API_KEY: ${{ secrets.ANGELONE_API_KEY }}
          ANGELONE_CLIENT_ID: ${{ secrets.ANGELONE_CLIENT_ID }}
          ANGELONE_PASSWORD: ${{ secrets.ANGELONE_PASSWORD }}
          ANGELONE_TOTP_SECRET: ${{ secrets.ANGELONE_TOTP_SECRET }}
          
          # Database & Other API Keys
          ANALYSIS_DB_URI: ${{ secrets.ANALYSIS_DB_URI }}
          SCHEDULER_DB_URI: ${{ secrets.SCHEDULER_DB_URI }}
          NEWSAPI_API_KEY: ${{ secrets.NEWSAPI_API_KEY }}
          
          # Email Configuration
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}

          # AI Provider Configuration (Azure OpenAI or Azure AI Foundry)
          AI_PROVIDER: ${{ secrets.AI_PROVIDER }}
          # Azure OpenAI credentials
          AZURE_AI_ENDPOINT: ${{ secrets.AZURE_AI_ENDPOINT }}
          AZURE_AI_API_KEY: ${{ secrets.AZURE_AI_API_KEY }}
          # Model names (provider-agnostic)
          AZURE_PRIMARY_DEPLOYMENT: ${{ secrets.AZURE_PRIMARY_DEPLOYMENT }}
          AZURE_SECONDARY_DEPLOYMENT: ${{ secrets.AZURE_SECONDARY_DEPLOYMENT }}
          # Backward compatibility
          AZURE_PRO_DEPLOYMENT: ${{ secrets.AZURE_PRO_DEPLOYMENT }}
          AZURE_FLASH_DEPLOYMENT: ${{ secrets.AZURE_FLASH_DEPLOYMENT }}
          # Azure AI Foundry inference (for models like Grok)
          AZURE_INFERENCE_ENDPOINT: ${{ secrets.AZURE_INFERENCE_ENDPOINT }}
          AZURE_INFERENCE_API_KEY: ${{ secrets.AZURE_INFERENCE_API_KEY }}
        run: python run_daily_jobs.py

      - name: Send Daily Report
        if: steps.market_check.outcome == 'success'
        env:
          ANALYSIS_DB_URI: ${{ secrets.ANALYSIS_DB_URI }}
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
        run: python send_daily_report.py