name: Scrybe AI - Daily Market Analysis

on:
  schedule:
    # Runs at 17:00 UTC Monday-Friday (which is 10:30 PM IST)
    - cron: '00 17 * * 1-5'
  workflow_dispatch:

jobs:
  run-daily-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Check if yesterday was a trading day
        id: market_check
        run: python check_market_open.py
        continue-on-error: true

      - name: Run Daily Analysis Script
        if: steps.market_check.outcome == 'success'
        env:
          # Angel One Credentials
          ANGELONE_API_KEY: ${{ secrets.ANGELONE_API_KEY }}
          ANGELONE_CLIENT_ID: ${{ secrets.ANGELONE_CLIENT_ID }}
          ANGELONE_PASSWORD: ${{ secrets.ANGELONE_PASSWORD }}
          ANGELONE_TOTP: ${{ secrets.ANGELONE_TOTP }}
          
          # Database & Other API Keys
          ANALYSIS_DB_URI: ${{ secrets.ANALYSIS_DB_URI }}
          SCHEDULER_DB_URI: ${{ secrets.SCHEDULER_DB_URI }}
          NEWSAPI_API_KEY: ${{ secrets.NEWSAPI_API_KEY }}
          
          # Email Configuration
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
          
          # Gemini API Key Pool
          GOOGLE_API_KEY_1: ${{ secrets.GOOGLE_API_KEY_1 }}
          GOOGLE_API_KEY_2: ${{ secrets.GOOGLE_API_KEY_2 }}
          GOOGLE_API_KEY_3: ${{ secrets.GOOGLE_API_KEY_3 }}
          GOOGLE_API_KEY_4: ${{ secrets.GOOGLE_API_KEY_4 }}
          GOOGLE_API_KEY_5: ${{ secrets.GOOGLE_API_KEY_5 }}
          GOOGLE_API_KEY_6: ${{ secrets.GOOGLE_API_KEY_6 }}
          GOOGLE_API_KEY_7: ${{ secrets.GOOGLE_API_KEY_7 }}
          GOOGLE_API_KEY_8: ${{ secrets.GOOGLE_API_KEY_8 }}
          GOOGLE_API_KEY_9: ${{ secrets.GOOGLE_API_KEY_9 }}
          GOOGLE_API_KEY_10: ${{ secrets.GOOGLE_API_KEY_10 }}
        run: python run_daily_jobs.py

      - name: Send Daily Report
        if: steps.market_check.outcome == 'success'
        env:
          ANALYSIS_DB_URI: ${{ secrets.ANALYSIS_DB_URI }}
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
        run: python send_daily_report.py