name: Scrybe AI - Manual Backtest Run

on:
  workflow_dispatch:
    inputs:
      batch_id:
        description: 'Unique ID for the backtest batch (e.g., AI_Candlestick_Apr25)'
        required: true
        default: 'MANUAL-RUN'
      start_date:
        description: 'Start date (YYYY-MM-DD)'
        required: true
        default: '2025-04-01' # Updated default example
      end_date:
        description: 'End date (YYYY-MM-DD)'
        required: true
        default: '2025-04-30' # Updated default example
      fresh_run:
        description: 'Delete previous data for this batch_id? (true/false)'
        required: true
        default: 'true'
      tickers:
        description: 'Optional: Tickers to test (e.g., RELIANCE.NS HDFCBANK.NS). Leave blank for full NSE universe.' # Description is okay, but update default examples above.
        required: false
        default: ''

jobs:
  run-unified-backtest:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # 6 hours (Keep this, full NSE backtest might be long)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      # --- ADDED TA-LIB C LIBRARY INSTALLATION ---
      - name: Install TA-Lib C Library Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential wget

      - name: Download and Install TA-Lib C Library
        run: |
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz && \
          tar -xzf ta-lib-0.4.0-src.tar.gz && \
          cd ta-lib/ && \
          ./configure --prefix=/usr && \
          make && \
          sudo make install
          cd ..
      # --- END ADDED STEPS ---

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # Ensure TA-Lib is listed in requirements.txt
          python -m pip install -r requirements.txt

      - name: Run Unified Backtesting Engine
        env:
          # Angel One Credentials
          ANGELONE_API_KEY: ${{ secrets.ANGELONE_API_KEY }}
          ANGELONE_CLIENT_ID: ${{ secrets.ANGELONE_CLIENT_ID }}
          ANGELONE_PASSWORD: ${{ secrets.ANGELONE_PASSWORD }}
          ANGELONE_TOTP_SECRET: ${{ secrets.ANGELONE_TOTP_SECRET }}

          # Database & Other API Keys
          ANALYSIS_DB_URI: ${{ secrets.ANALYSIS_DB_URI }}
          SCHEDULER_DB_URI: ${{ secrets.SCHEDULER_DB_URI }}
          NEWSAPI_API_KEY: ${{ secrets.NEWSAPI_API_KEY }} # Still needed if data_retriever imports it

          # --- Azure AI Credentials & Deployments ---
          AZURE_AI_ENDPOINT: ${{ secrets.AZURE_AI_ENDPOINT }}
          AZURE_AI_API_KEY: ${{ secrets.AZURE_AI_API_KEY }}
          AZURE_PRO_DEPLOYMENT: ${{ secrets.AZURE_PRO_DEPLOYMENT }}
          AZURE_FLASH_DEPLOYMENT: ${{ secrets.AZURE_FLASH_DEPLOYMENT }}

        run: |
          python main_orchestrator.py \
            --batch_id ${{ github.event.inputs.batch_id }} \
            --start_date ${{ github.event.inputs.start_date }} \
            --end_date ${{ github.event.inputs.end_date }} \
            --fresh_run ${{ github.event.inputs.fresh_run }} \
            ${{ github.event.inputs.tickers && '--tickers' }} ${{ github.event.inputs.tickers }} # Correctly handles optional tickers argument