name: Run Apex AI Backtest

on:
  workflow_dispatch:
    inputs:
      batch_id:
        description: 'Unique ID for the backtest batch'
        required: true
        default: 'APEX-V2-MANUAL-RUN'
      start_date:
        description: 'Start date (YYYY-MM-DD)'
        required: true
        default: '2025-07-01'
      end_date:
        description: 'End date (YYYY-MM-DD)'
        required: true
        default: '2025-08-29'

jobs:
  run-backtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Orchestrator
        run: python main_orchestrator.py --batch_id ${{ github.event.inputs.batch_id }} --start_date ${{ github.event.inputs.start_date }} --end_date ${{ github.event.inputs.end_date }} --fresh_run True
        env:
          ANALYSIS_DB_URI: ${{ secrets.ANALYSIS_DB_URI }}
          SCHEDULER_DB_URI: ${{ secrets.SCHEDULER_DB_URI }}
          GOOGLE_API_KEY_1: ${{ secrets.GOOGLE_API_KEY_1 }}
          GOOGLE_API_KEY_2: ${{ secrets.GOOGLE_API_KEY_2 }}
          GOOGLE_API_KEY_3: ${{ secrets.GOOGLE_API_KEY_3 }}
          GOOGLE_API_KEY_4: ${{ secrets.GOOGLE_API_KEY_4 }}
          GOOGLE_API_KEY_5: ${{ secrets.GOOGLE_API_KEY_5 }}
          GOOGLE_API_KEY_6: ${{ secrets.GOOGLE_API_KEY_6 }}
          GOOGLE_API_KEY_7: ${{ secrets.GOOGLE_API_KEY_7 }}
          GOOGLE_API_KEY_8: ${{ secrets.GOOGLE_API_KEY_8 }}
          GOOGLE_API_KEY_9: ${{ secrets.GOOGLE_API_KEY_9 }}
          GOOGLE_API_KEY_10: ${{ secrets.GOOGLE_API_KEY_10 }}
          NEWSAPI_API_KEY: ${{ secrets.NEWSAPI_API_KEY }}
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          
      - name: Run Stateful Backtester
        run: python stateful_backtester.py --batch_id ${{ github.event.inputs.batch_id }}
        env:
          SCHEDULER_DB_URI: ${{ secrets.SCHEDULER_DB_URI }}
          ANALYSIS_DB_URI: ${{ secrets.ANALYSIS_DB_URI }}