name: Scrybe AI - Manual Fundamentals Update

on:
  workflow_dispatch: # Allows you to run it manually from the Actions tab

jobs:
  run-fundamentals-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      # TA-Lib installation steps have been correctly REMOVED as they are not needed for this script.

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # Note: If TA-Lib is in requirements.txt, this step might fail.
          # If it does, you will need to add the TA-Lib C-library installation steps back.
          python -m pip install -r requirements.txt

      - name: Run Fundamentals Update Script
        env:
          # --- FIX: ADDED ALL REQUIRED SECRETS ---
          # Although this script uses yfinance, the login is triggered on import
          # because config.DATA_SOURCE is set to 'angelone'.
          ANALYSIS_DB_URI: ${{ secrets.ANALYSIS_DB_URI }}
          ANGELONE_API_KEY: ${{ secrets.ANGELONE_API_KEY }}
          ANGELONE_CLIENT_ID: ${{ secrets.ANGELONE_CLIENT_ID }}
          ANGELONE_PASSWORD: ${{ secrets.ANGELONE_PASSWORD }}
          ANGELONE_TOTP_SECRET: ${{ secrets.ANGELONE_TOTP_SECRET }}
          # --- END FIX ---
        run: python update_fundamentals.py
